feature: init i18n
IBM/ibm-storage-odf-console pull request #24
Opened 2021-07-28 11:11 UTC by shdn-ibm

2021-08-04 08:52 UTC, afreen23 requested changes
The namespace and filename are not as per the suggested format.
See the [guidelines](https://github.com/jhadvig/enhancements/blob/3d22f331d99a7ec4ff0d9ce5b4f4e006d159d5a0/enhancements/console/dynamic-plugins.md#localization)

2021-08-06 09:04 UTC, shdn-ibm commented
After integration testing with latest console, dynamic plugin translation does not work. please hold this pr until the issue solved

2021-09-01 08:18 UTC, afreen23 requested changes

2021-09-01 08:18 UTC, afreen23 commented on i18n-scripts/consolidate-public-folders.js
> +common.findLocalesFolder(localPath, iterateThroughLocalesFolder);
You dont need these consolidation files.
Since you have just one package unlike console

2021-09-01 08:18 UTC, afreen23 commented on src/components/raw-capacity-card/raw-capacity-card.tsx
> +                )}
just t() would be fine since you are adding namespace in hook.

2021-09-01 08:18 UTC, afreen23 commented on src/components/raw-capacity-card/raw-capacity-card.tsx
> +  //const { t } = useTranslation("plugin__ibm-storage-odf-plugin");
why commented ?

2021-09-01 08:19 UTC, afreen23 requested changes

2021-09-01 08:19 UTC, afreen23 commented on .vscode/launch.json
> +}
added by miss ?

2021-09-01 08:19 UTC, afreen23 commented on .vscode/tasks.json
> +}
added by miss ?

2021-09-01 08:24 UTC, afreen23 requested changes

2021-09-01 08:24 UTC, afreen23 commented on i18n-scripts/common.js
> +};
Yo8u might also dont require this for your package.

2021-09-01 08:24 UTC, afreen23 commented on i18n-scripts/languages.sh
> +export LANGUAGES=( 'ja' 'zh-cn' 'ko')
Its not sued anywhere.

2021-09-03 07:19 UTC, afreen23 requested changes

2021-09-03 07:19 UTC, afreen23 commented on src/components/details-card/details-card.tsx
> +      : "unknown";
This will who then "https:unknown " ?
I think you would rather want to say "Not available"
```suggestion
      : null;
```

2021-09-03 07:19 UTC, afreen23 commented on src/components/details-card/details-card.tsx
> +              />
```suggestion
              endpointAddress ? <ExternalLink
                href={"https://" + endpointAddress}
                text="IBM flashsystem"
              /> : t('Not available')
```

2021-09-03 07:19 UTC, afreen23 commented on src/components/details-card/details-card.tsx
> +      : "unknown";
same for this
```suggestion
      : t('Not available');
```

2021-09-03 07:19 UTC, afreen23 commented on src/components/details-card/details-card.tsx
> +        : "unknown",
```suggestion
      secretloaded && !secretloadError && secretData
        ? Base64.decode(secretData)
        : null
```

2021-09-03 07:19 UTC, afreen23 commented on src/components/raw-capacity-card/raw-capacity-card.tsx
> +                )}
@shdn-ibm ^^

2021-09-08 05:15 UTC, shdn-ibm commented
merge code into main for integration testing

2021-09-08 05:15 UTC, merged